### ISSUE TITLE
Docs missing fetch step for merge-pr

### ISSUE THREAD

**Issue by windwardrail** [PolySync/kevlar-laces#42]
The merge-pr command fails if the remote branch is not first fetched. The docs omit this step in the usage instructions.

**Comment by gchronis** [comment]
@windwardrail merge-pr should do the fetching for you. We have seen this a few times now. I'm going to try to figure out the conditions under which it fails, or if we did something somewhere along the line to make it fail always if local copies of the branches are out of date
